### ISSUE TITLE
Package size & version

### ISSUE THREAD

**Issue by Siilwyn** [ianstormtaylor/read-file-stdin#6]
The package is pretty big because it includes the 'test' directory, this [has been fixed](https://github.com/ianstormtaylor/read-file-stdin/commit/e968aa80bc3a66c4d3d5f7e448c3ad038c43f6e3) but never got published to NPM. Could you publish it?

While you are publishing it would be a good idea to bump the version to 1.0.0 since this package isn't in any kind of experimental state.

**Comment by ianstormtaylor** [comment]
Swapped to an `.npmignore` file and published as `0.2.1`, let me know if that doesn't help!

**Comment by Siilwyn** [comment]
Thank you!
I prefer the `files` field in a `package.json` over a seperate `.npmignore` file but this solves it too. :+1:
